### ISSUE TITLE
Broken link in Gensim.md

### ISSUE THREAD

**Issue by harshit-sh** [jxieeducation/DIY-Data-Science#1]
The [Intuition link](https://github.com/jxieeducation/DIY-Data-Science/blob/master/tedunderwood.com/2012/04/07/topic-modeling-made-just-simple-enough) for LDA in **gensim.md** seems to be broken. Getting a 404 error. Nice compilation btw!

**Comment by jxieeducation** [comment]
Thanks Harshit! Fixed! 

https://tedunderwood.com/2012/04/07/topic-modeling-made-just-simple-enough/

Ted Underwood's explanation is really great! He also outlines a lot of applications of LDA from a literary and historical perspective =)

**Comment by harshit-sh** [comment]
That link is awesome! Great work on the others as well. The seq2seq guide is too good! :)
